import React,{useEffect,useRef}from'react';
import styled from'@emotion/styled';
import{ArrowLeft,Pause,Volume2}from'lucide-react';

const Screen=styled('div')({
  position:'fixed',inset:0,zIndex:60,width:'100vw',height:'100dvh',overflow:'hidden',padding:10,color:'#f4f8ff',background:'radial-gradient(circle at 18% 10%,#2167da47,transparent 28%),radial-gradient(circle at 85% 12%,#a45cff24,transparent 23%),linear-gradient(#07101b,#03060b)',
  '.shell':{width:'min(1180px,100%)',height:'100%',margin:'0 auto',display:'flex',flexDirection:'column',alignItems:'center',overflow:'hidden'},
  '.topbar':{flex:'0 0 auto',width:'100%',minHeight:50,display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,padding:'8px 10px',marginBottom:8,border:'1px solid #59f3ff29',borderRadius:14,background:'linear-gradient(#0c1827f5,#07101af5)',boxShadow:'0 16px 45px #0006'},
  '.brand':{display:'flex',alignItems:'center',gap:8,minWidth:0},'.brand-mark':{width:34,height:34,borderRadius:10,display:'grid',placeItems:'center',color:'#07110c',fontWeight:1000,background:'linear-gradient(145deg,#d6ff80,#70f5ad,#5ceaff)'},'.brand-copy':{display:'flex',flexDirection:'column'},'.brand-copy strong':{fontSize:'.78rem',letterSpacing:'.09em'},'.brand-copy span':{fontSize:'.55rem',color:'#718697',marginTop:4},
  '.back-btn,.icon-btn,.pause-btn':{minHeight:34,border:'1px solid #ffffff1a',background:'#081727',color:'#eaf7ff',borderRadius:10,display:'inline-flex',alignItems:'center',justifyContent:'center',cursor:'pointer'},'.back-btn':{width:34,padding:0},'.icon-btn':{width:36,padding:0},'.pause-btn':{gap:6,padding:'0 10px',fontSize:'.68rem',fontWeight:900},
  '.hud':{display:'flex',alignItems:'center',justifyContent:'flex-end',gap:6,flexWrap:'wrap',fontWeight:850},'.hud>span':{minHeight:34,padding:'7px 10px',borderRadius:999,border:'1px solid #ffffff17',background:'#071624',display:'inline-flex',alignItems:'center',fontSize:'.72rem'},
  '.game-wrap':{position:'relative',flex:'0 0 auto',margin:'auto',maxWidth:'100%',maxHeight:'calc(100dvh - 72px)',aspectRatio:'16/9',overflow:'hidden',borderRadius:18,border:'1px solid #59f3ff33',background:'#071522',boxShadow:'0 28px 85px #000a,0 0 45px #59f3ff0c'},
  '#game':{display:'block',width:'100%',height:'100%',maxWidth:'100%',maxHeight:'100%',objectFit:'contain',touchAction:'none'},
  '.tip-bar':{position:'absolute',left:12,bottom:12,zIndex:3,padding:'8px 11px',borderRadius:10,border:'1px solid #59f3ff21',background:'#050e18c7',color:'#cfe9f5',fontSize:'.72rem',backdropFilter:'blur(8px)'},
  '.overlay':{position:'absolute',inset:0,zIndex:6,display:'none',alignItems:'center',justifyContent:'center',padding:12,overflow:'hidden',background:'radial-gradient(circle at 50% 30%,#13375dcc,#03080ee8 68%)',backdropFilter:'blur(5px)'},'.overlay.visible':{display:'flex'},
  '.card':{width:'min(540px,calc(100% - 24px))',maxWidth:'min(540px,calc(100% - 24px))',maxHeight:'calc(100% - 20px)',overflow:'hidden',padding:'20px 22px',borderRadius:22,textAlign:'center',border:'1px solid #59f3ff29',background:'linear-gradient(145deg,#0d1f33f7,#07121ff9)',boxShadow:'0 28px 85px #000a'},
  '.game-card-head':{display:'flex',alignItems:'center',justifyContent:'center',gap:13,textAlign:'left'},'.mascot-badge':{width:58,height:58,minWidth:58,borderRadius:17,display:'grid',placeItems:'center',fontSize:38,background:'#071624',border:'1px solid #ffffff1a'},'.eyebrow':{fontSize:'.55rem',fontWeight:950,letterSpacing:'.18em',color:'#59f3ff'},'.card h1':{margin:'4px 0 0',fontSize:'clamp(1.65rem,4vw,2.25rem)',lineHeight:1,letterSpacing:'-.035em'},'.compact-description':{margin:'11px auto',maxWidth:470,color:'#b9cfde',fontSize:'.82rem',lineHeight:1.45},
  '.feature-row':{display:'flex',justifyContent:'center',gap:6,flexWrap:'wrap',margin:'9px 0'},'.feature-row span':{padding:'5px 7px',borderRadius:999,background:'#061522',border:'1px solid #ffffff17',fontSize:'.64rem',color:'#b9d0df'},
  '.pilot-field':{display:'grid',gap:5,textAlign:'left',maxWidth:290,margin:'9px auto 0'},'.pilot-field span':{fontSize:'.58rem',textTransform:'uppercase',letterSpacing:'.12em',color:'#7890a2',fontWeight:900},'.pilot-field input':{width:'100%',border:'1px solid #59f3ff2e',borderRadius:10,padding:'8px 10px',background:'#04111e',color:'#fff',outline:'none'},'.pilot-field input:focus':{borderColor:'#59f3ff',boxShadow:'0 0 0 3px #59f3ff14'},
  '.game-card-actions':{display:'flex',alignItems:'center',justifyContent:'center',gap:12,flexWrap:'wrap',marginTop:11},'.controls':{margin:0,color:'#8098aa',fontSize:'.67rem'},'#startBtn':{border:0,borderRadius:999,padding:'10px 17px',cursor:'pointer',fontSize:'.76rem',fontWeight:1000,color:'#061009',background:'linear-gradient(135deg,#75f7ff,#a9ff6a)',boxShadow:'0 12px 30px #59f3ff26'},
  '.wave-banner':{position:'absolute',left:'50%',top:'17%',zIndex:5,transform:'translate(-50%,-14px) scale(.96)',opacity:0,pointerEvents:'none',padding:'11px 18px',borderRadius:12,background:'#071625e8',border:'1px solid #59f3ff2e',color:'#fff',fontSize:'1rem',fontWeight:950,letterSpacing:'.06em',transition:'.2s'},'.wave-banner.show':{opacity:1,transform:'translate(-50%,0) scale(1)'},
  '.mobile-controls':{display:'none',position:'absolute',right:10,bottom:10,zIndex:4},'.dpad':{display:'grid',gridTemplateColumns:'40px 40px 40px',gridTemplateRows:'40px 40px 40px',gap:4},'.dpad button':{border:'1px solid #ffffff29',background:'#061624d8',color:'#fff',borderRadius:10,fontWeight:900,touchAction:'none'},'.dpad button:nth-of-type(1)':{gridColumn:2,gridRow:1},'.dpad button:nth-of-type(2)':{gridColumn:1,gridRow:2},'.dpad button:nth-of-type(3)':{gridColumn:2,gridRow:2},'.dpad button:nth-of-type(4)':{gridColumn:3,gridRow:2},'.engine-cache':{display:'none!important'},
  '@media(max-width:720px)':{padding:5,'.topbar':{minHeight:42,padding:'5px 6px',marginBottom:5,borderRadius:10},'.brand-copy':{display:'none'},'.brand-mark,.back-btn':{width:29,height:29,borderRadius:8},'.hud':{gap:3,fontSize:'.63rem'},'.hud>span,.pause-btn,.icon-btn':{minHeight:27,padding:'4px 6px'},'.icon-btn':{width:29},'.pause-btn':{fontSize:'.58rem'},'.game-wrap':{maxHeight:'calc(100dvh - 48px)',borderRadius:11},'.tip-bar':{left:7,right:135,bottom:7,fontSize:'.58rem',padding:'6px 8px'},'.mobile-controls':{display:'block'},'.card':{width:'min(500px,calc(100% - 10px))',maxWidth:'min(500px,calc(100% - 10px))',padding:13},'.mascot-badge':{width:44,height:44,minWidth:44,fontSize:29,borderRadius:13},'.card h1':{fontSize:'1.45rem'},'.compact-description':{fontSize:'.7rem',margin:'7px auto'},'.feature-row':{margin:'6px 0'},'.feature-row span':{fontSize:'.56rem',padding:'4px 5px'},'.pilot-field':{marginTop:6},'.pilot-field input':{padding:'6px 8px'},'.game-card-actions':{marginTop:7,gap:7},'.controls':{fontSize:'.57rem'},'#startBtn':{padding:'8px 12px',fontSize:'.68rem'}},
  '@media(max-width:430px)':{'.hud #combo,.hud #wave':{display:'none'},'.controls':{display:'none'},'.dpad':{gridTemplateColumns:'36px 36px 36px',gridTemplateRows:'36px 36px 36px'}}
});

export default function GameScreen({active,onBack}){
  const root=useRef(null),wrap=useRef(null),top=useRef(null);
  useEffect(()=>{import('../game.js').catch(err=>console.error('Game engine failed to load',err))},[]);
  useEffect(()=>{const fit=()=>{if(!active||!root.current||!wrap.current)return;const shell=root.current.querySelector('.shell');const w=Math.max(220,shell?.clientWidth||0),h=Math.max(150,root.current.clientHeight-(top.current?.offsetHeight||48)-12),ratio=16/9;let width=Math.min(w,h*ratio),height=width/ratio;if(height>h){height=h;width=height*ratio}wrap.current.style.width=Math.floor(width)+'px';wrap.current.style.height=Math.floor(height)+'px'};if(active){document.body.style.overflow='hidden';requestAnimationFrame(fit);const t=setTimeout(fit,80);window.addEventListener('resize',fit,{passive:true});return()=>{clearTimeout(t);window.removeEventListener('resize',fit);document.body.style.overflow=''}}document.body.style.overflow=''},[active]);
  const back=()=>{const p=document.getElementById('pauseBtn');if(p&&p.textContent.includes('Pause'))p.click();onBack()};
  return <Screen ref={root} style={{display:active?'block':'none'}}>
    <main className="shell"><header className="topbar" ref={top}><div className="brand"><button className="back-btn" onClick={back} aria-label="Return to game library"><ArrowLeft size={16}/></button><div className="brand-mark">Z</div><div className="brand-copy"><strong>SKY CRYSTAL RUN</strong><span>ARCADE SURVIVAL</span></div></div><div className="hud"><span id="score">💎 0</span><span id="combo">⚡ x1</span><span id="health">❤️❤️❤️</span><span id="wave">🌊 1</span><span id="best">🏆 0</span><button id="soundBtn" className="icon-btn" aria-label="Toggle sound"><Volume2 size={14}/></button><button id="pauseBtn" className="pause-btn"><Pause size={13}/> Pause</button></div></header>
      <section className="game-wrap" ref={wrap}><canvas id="game" width="960" height="540" aria-label="Sky Crystal Run game canvas"/><div id="mobileControls" className="mobile-controls"><div className="dpad"><button data-key="arrowup">▲</button><button data-key="arrowleft">◀</button><button data-key="arrowdown">▼</button><button data-key="arrowright">▶</button></div></div><div id="tipBar" className="tip-bar">Collect crystals • Chain combos • Survive each wave</div>
        <div id="overlay" className="overlay visible"><div className="card"><div className="game-card-head"><div className="mascot-badge">🐉</div><div><div className="eyebrow">ARCADE FLIGHT</div><h1>Sky Crystal Run</h1></div></div><p id="overlayText" className="compact-description">Fly through changing skies, chain crystals, grab power-ups, and survive increasingly dangerous waves.</p><div className="feature-row"><span>💎 Combos</span><span>🛡 Power-ups</span><span>🔥 Boss waves</span><span>🏆 Ranked</span></div><label className="pilot-field"><span>Pilot name</span><input id="playerName" maxLength="16" autoComplete="off" autoCorrect="off" spellCheck="false" inputMode="text" required/></label><div className="game-card-actions"><p className="controls">WASD / Arrow Keys · Drag on mobile · P to pause</p><button id="startBtn">Start Adventure</button></div></div></div>
        <div id="waveBanner" className="wave-banner"/>
      </section><div className="engine-cache"><span id="leaderboardStatus"/><ol id="leaderboard"/></div>
    </main>
  </Screen>
}