import React,{useEffect,useState}from'react';
import styled from'@emotion/styled';
import{Activity,ArrowRight,ArrowUpRight,Cpu,Crosshair,Gamepad2,Globe2,Hexagon,Play,Shield,Trophy}from'lucide-react';
import{fetchLeaderboard}from'../leaderboard.js';

const Page=styled('div')({
  '--cyan':'#59f3ff','--purple':'#a45cff','--red':'#ff416c','--lime':'#a9ff6a',
  minHeight:'100vh',color:'#f4f8ff',background:'radial-gradient(circle at 16% 8%,#174c9a44,transparent 28%),radial-gradient(circle at 83% 16%,#7d35ff33,transparent 25%),#05070b',overflow:'hidden',
  '*':{boxSizing:'border-box'},
  '.wrap':{width:'min(1260px,calc(100% - 36px))',margin:'auto'},
  '.nav':{height:72,position:'sticky',top:0,zIndex:20,display:'flex',alignItems:'center',gap:26,background:'linear-gradient(#05070bf5,#05070b88,transparent)',backdropFilter:'blur(14px)'},
  '.brand':{display:'flex',alignItems:'center',gap:10,textDecoration:'none',color:'#fff'},
  '.logo':{width:40,height:40,borderRadius:12,display:'grid',placeItems:'center',fontWeight:1000,color:'#06100b',background:'linear-gradient(145deg,#d7ff80,#6bf0ad,#58eaff)',boxShadow:'0 0 28px #67ff9a33'},
  '.brandtext':{display:'flex',flexDirection:'column'},
  '.brandtext b':{letterSpacing:'.17em',fontSize:'.9rem'},'.brandtext small':{marginTop:4,color:'#708292',fontSize:'.55rem',letterSpacing:'.3em'},
  '.links':{display:'flex',gap:24,marginLeft:'auto'},'.links a':{color:'#8194a4',textDecoration:'none',fontSize:'.76rem',fontWeight:800},'.links a:hover':{color:'#fff'},
  '.navbtn':{display:'flex',alignItems:'center',gap:8,padding:'9px 12px',border:'1px solid #ffffff1f',borderRadius:10,color:'#eaf7ff',textDecoration:'none',fontSize:'.66rem',fontWeight:900,textTransform:'uppercase',background:'#ffffff0a'},
  '.navbtn svg':{color:'var(--lime)'},
  '.hero':{minHeight:690,padding:'72px 0 92px',display:'grid',gridTemplateColumns:'minmax(0,.92fr) minmax(480px,1.08fr)',gap:64,alignItems:'center'},
  '.kicker':{display:'flex',alignItems:'center',gap:8,color:'var(--cyan)',fontSize:'.64rem',fontWeight:900,letterSpacing:'.17em'},
  '.kicker i':{width:7,height:7,borderRadius:'50%',background:'var(--lime)',boxShadow:'0 0 12px var(--lime)'},
  'h1':{margin:'17px 0 20px',fontSize:'clamp(4rem,7.2vw,6.8rem)',lineHeight:.84,letterSpacing:'-.065em',textTransform:'uppercase'},
  'h1 span':{display:'block',color:'transparent',WebkitTextStroke:'1px #6ef4ffcc',textShadow:'0 0 42px #59f3ff1c'},
  '.lead':{maxWidth:650,color:'#879baa',lineHeight:1.7,fontSize:'1rem'},
  '.actions':{display:'flex',gap:10,marginTop:28,flexWrap:'wrap'},
  '.primary,.secondary':{minHeight:50,padding:'0 18px',borderRadius:11,display:'inline-flex',alignItems:'center',justifyContent:'center',gap:9,fontSize:'.77rem',fontWeight:950,cursor:'pointer'},
  '.primary':{background:'linear-gradient(135deg,var(--cyan),var(--purple))',color:'#05070b',textDecoration:'none',border:0},
  '.secondary':{background:'#ffffff09',color:'#edf8ff',border:'1px solid #ffffff20'},
  '.stats':{display:'flex',gap:28,marginTop:40,flexWrap:'wrap'},'.stats div':{display:'flex',flexDirection:'column'},'.stats small':{fontSize:'.5rem',color:'#526777',letterSpacing:'.14em'},'.stats b':{marginTop:5,fontSize:'.8rem',letterSpacing:'.06em'},
  '.console':{border:'1px solid #ffffff20',borderRadius:24,background:'linear-gradient(145deg,#0d1724,#060a10)',boxShadow:'0 38px 110px #000b',overflow:'hidden'},
  '.consolebar':{height:44,padding:'0 14px',display:'flex',alignItems:'center',justifyContent:'space-between',borderBottom:'1px solid #ffffff12',color:'#627686',fontSize:'.55rem',fontWeight:900,letterSpacing:'.14em'},
  '.online':{color:'#72f59a'},
  '.consolegrid':{padding:16,display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:11},
  '.core':{minHeight:310,position:'relative',overflow:'hidden',borderRadius:17,border:'1px solid #59f3ff22',background:'radial-gradient(circle at 50% 45%,#59f3ff17,transparent 28%),#07111b'},
  '.floor':{position:'absolute',left:'-10%',right:'-10%',bottom:'-25%',height:'70%',transform:'perspective(420px) rotateX(67deg)',transformOrigin:'bottom',backgroundImage:'linear-gradient(#59f3ff22 1px,transparent 1px),linear-gradient(90deg,#59f3ff22 1px,transparent 1px)',backgroundSize:'34px 34px'},
  '.orb':{position:'absolute',left:'50%',top:'47%',transform:'translate(-50%,-50%)',width:120,height:120,borderRadius:34,display:'grid',placeItems:'center',color:'#05070b',background:'radial-gradient(circle at 35% 28%,#e2ffff,#69efff 28%,#9f5cff 65%,#321e52)',boxShadow:'0 0 50px #59f3ff55,0 0 100px #a45cff33'},
  '.orb:before,.orb:after':{content:'""',position:'absolute',borderRadius:'50%'},'.orb:before':{inset:-52,border:'1px solid #59f3ff44'},'.orb:after':{inset:-98,border:'1px dashed #a45cff3a'},
  '.micro':{position:'absolute',padding:'6px 8px',border:'1px solid #ffffff17',borderRadius:8,background:'#06101bd9',color:'#8096a7',fontSize:'.48rem',fontWeight:900,letterSpacing:'.1em'},
  '.m1':{left:'7%',top:'17%'},'.m2':{right:'6%',top:'28%'},'.m3':{left:'10%',bottom:'15%'},
  '.side':{display:'grid',gap:11},'.databox':{border:'1px solid #ffffff15',borderRadius:15,background:'#ffffff05',padding:14,display:'flex',flexDirection:'column',justifyContent:'space-between'},
  '.databox header':{display:'flex',justifyContent:'space-between',color:'#607586',fontSize:'.49rem',letterSpacing:'.12em'},'.databox svg':{color:'var(--cyan)'},'.databox strong':{fontSize:'1.45rem'},'.databox p':{margin:'5px 0 0',color:'#607485',fontSize:'.63rem'},
  '.consolefoot':{display:'grid',gridTemplateColumns:'repeat(3,1fr)',borderTop:'1px solid #ffffff12'},'.consolefoot div':{padding:12,background:'#080d14',display:'flex',alignItems:'center',gap:8},'.consolefoot svg':{width:15,color:'var(--cyan)'},'.consolefoot span':{display:'flex',flexDirection:'column'},'.consolefoot small':{fontSize:'.45rem',color:'#4e6272'},'.consolefoot b':{fontSize:'.62rem',marginTop:3},
  '.rail':{borderBlock:'1px solid #ffffff10',background:'#080d14aa'},'.railin':{display:'flex',gap:23,padding:'12px 0',overflow:'hidden'},'.rail span':{fontSize:'.58rem',fontWeight:900,letterSpacing:'.17em',color:'#5d7282'},'.rail i':{fontStyle:'normal',color:'var(--purple)'},
  '.section':{padding:'100px 0'},'.sectionhead':{display:'flex',justifyContent:'space-between',alignItems:'end',gap:30,marginBottom:31},'.sectionhead span,.copy>span':{color:'var(--cyan)',fontSize:'.58rem',fontWeight:900,letterSpacing:'.18em'},'.sectionhead h2,.copy h2':{margin:'7px 0 0',fontSize:'clamp(2.2rem,4vw,3.8rem)',letterSpacing:'-.05em'},'.sectionhead p':{maxWidth:460,margin:0,color:'#697e8e',lineHeight:1.6},
  '.gamecard':{display:'grid',gridTemplateColumns:'minmax(420px,1.08fr) minmax(0,.92fr)',border:'1px solid #ffffff18',borderRadius:24,overflow:'hidden',background:'linear-gradient(145deg,#0c131d,#070b12)',boxShadow:'0 30px 95px #0008',cursor:'pointer'},
  '.art':{minHeight:500,position:'relative',overflow:'hidden',background:'radial-gradient(circle at 72% 22%,#7ff7ff88,transparent 10%),radial-gradient(circle at 34% 30%,#635aff55,transparent 28%),linear-gradient(155deg,#103960,#151b48 47%,#081018)'},
  '.art:before':{content:'""',position:'absolute',inset:0,backgroundImage:'linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px)',backgroundSize:'34px 34px'},
  '.sun':{position:'absolute',width:145,height:145,borderRadius:'50%',right:'15%',top:'18%',background:'radial-gradient(circle,#efffff,#64efff 28%,#865cff 58%,transparent 70%)',boxShadow:'0 0 70px #59f3ff66'},
  '.mount':{position:'absolute',left:'-8%',right:'-8%',bottom:'-2%',height:'50%',background:'#07111d',clipPath:'polygon(0 74%,12% 55%,22% 67%,37% 36%,51% 69%,64% 43%,75% 62%,87% 32%,100% 68%,100% 100%,0 100%)'},
  '.crystal':{position:'absolute',width:27,height:62,background:'linear-gradient(#efffff,#59eaff 45%,#6f4cff)',clipPath:'polygon(50% 0,100% 34%,72% 100%,26% 100%,0 34%)',boxShadow:'0 0 24px #59f3ff66'},'.c1':{left:'20%',top:'24%',transform:'rotate(12deg)'},'.c2':{left:'48%',top:'50%',transform:'scale(.72) rotate(-16deg)'},'.c3':{right:'18%',bottom:'22%',transform:'scale(.85) rotate(24deg)'},
  '.arttop':{position:'absolute',left:17,right:17,top:17,display:'flex',justifyContent:'space-between',color:'#8ca0b0',fontSize:'.54rem',letterSpacing:'.13em'},'.live':{color:'#75f59c'},
  '.arttitle':{position:'absolute',left:25,bottom:25},'.arttitle small':{color:'var(--cyan)',fontSize:'.54rem',letterSpacing:'.17em'},'.arttitle b':{display:'block',marginTop:7,fontSize:'clamp(3rem,5vw,5.2rem)',lineHeight:.78,letterSpacing:'-.05em'},
  '.playorb':{position:'absolute',right:23,bottom:23,width:62,height:62,borderRadius:'50%',border:0,background:'#f2fff6',color:'#05070b',display:'grid',placeItems:'center',cursor:'pointer'},
  '.gamecopy':{padding:'38px 40px',display:'flex',flexDirection:'column',justifyContent:'center'},'.gamecopy>span':{color:'var(--cyan)',fontSize:'.58rem',letterSpacing:'.17em',fontWeight:900},'.gamecopy h3':{margin:'10px 0 13px',fontSize:'clamp(2.4rem,4vw,4rem)',letterSpacing:'-.05em'},'.gamecopy>p':{margin:0,color:'#8296a6',lineHeight:1.65},
  '.specs':{display:'grid',gridTemplateColumns:'1fr 1fr',gap:9,marginTop:25},'.specs div':{padding:12,border:'1px solid #ffffff13',borderRadius:10,background:'#ffffff05'},'.specs small':{display:'block',color:'#526777',fontSize:'.48rem',letterSpacing:'.13em'},'.specs b':{display:'block',marginTop:5,fontSize:'.72rem'},
  '.enter':{display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,marginTop:28,paddingTop:21,borderTop:'1px solid #ffffff12'},'.enter button':{border:0,background:'none',color:'var(--lime)',fontSize:'.7rem',fontWeight:900,letterSpacing:'.09em',cursor:'pointer'},'.enter small':{fontSize:'.5rem',color:'#516777',letterSpacing:'.13em'},
  '.twocol':{display:'grid',gridTemplateColumns:'minmax(0,.86fr) minmax(420px,1.14fr)',gap:64,alignItems:'center',paddingTop:18},'.copy p':{color:'#7d91a1',lineHeight:1.65},
  '.ranking':{padding:21,border:'1px solid #ffffff17',borderRadius:20,background:'linear-gradient(145deg,#0b111a,#060a10)'},'.rankhead':{display:'flex',justifyContent:'space-between',paddingBottom:14,borderBottom:'1px solid #ffffff12'},'.rankhead div':{display:'flex',flexDirection:'column'},'.rankhead small':{fontSize:'.48rem',color:'#536879',letterSpacing:'.13em'},'.rankhead b':{fontSize:'.85rem',marginTop:4},'.status':{fontSize:'.5rem',color:'#73f69a',border:'1px solid #6dff9633',padding:'5px 7px',borderRadius:999,height:'max-content'},
  '.ranklist':{listStyle:'none',margin:0,padding:0},'.ranklist li':{display:'grid',gridTemplateColumns:'36px 1fr auto',gap:9,alignItems:'center',padding:'12px 0',borderTop:'1px solid #ffffff0c'},'.ranklist em':{fontStyle:'normal',color:'#4d6271',fontSize:'.6rem'},'.ranklist div':{display:'flex',flexDirection:'column',minWidth:0},'.ranklist b':{fontSize:'.8rem'},'.ranklist small':{marginTop:3,color:'#536a79',fontSize:'.56rem'},'.ranklist strong':{color:'var(--cyan)',fontSize:'.86rem'},
  '.footer':{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,padding:'28px 0 36px',borderTop:'1px solid #ffffff12',color:'#4d6272',fontSize:'.64rem'},
  '@media(max-width:1000px)':{'.hero':{gridTemplateColumns:'1fr',minHeight:'auto'},'.gamecard':{gridTemplateColumns:'1fr'},'.twocol':{gridTemplateColumns:'1fr'},'.console':{maxWidth:850}},
  '@media(max-width:720px)':{'.wrap':{width:'calc(100% - 20px)'},'.nav':{height:58,backdropFilter:'none',background:'#05070bf2'},'.brandtext small':{display:'none'},'.links':{display:'none'},'.navbtn':{marginLeft:'auto',width:36,height:36,padding:0,justifyContent:'center'},'.navbtn span':{display:'none'},'.hero':{padding:'38px 0 56px',gap:32},'.kicker':{fontSize:'.55rem',letterSpacing:'.11em'},'h1':{fontSize:'clamp(2.8rem,15vw,4.5rem)'},'.lead':{fontSize:'.9rem'},'.actions':{display:'grid'},'.primary,.secondary':{width:'100%'},'.stats':{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:25},'.stats div':{padding:9,border:'1px solid #ffffff12',borderRadius:9,background:'#ffffff05'},'.stats div:last-child':{gridColumn:'1/-1'},'.console':{borderRadius:17},'.consolegrid':{gridTemplateColumns:'1fr'},'.core':{minHeight:225},'.side':{gridTemplateColumns:'1fr 1fr'},'.section':{padding:'70px 0'},'.sectionhead':{alignItems:'flex-start',flexDirection:'column',gap:10},'.sectionhead h2,.copy h2':{fontSize:'clamp(2rem,10vw,3rem)'},'.art':{minHeight:275},'.sun':{width:95,height:95},'.arttitle':{left:17,bottom:17},'.arttitle b':{fontSize:'3rem'},'.playorb':{width:50,height:50,right:15,bottom:15},'.gamecopy':{padding:'22px 17px'},'.gamecopy h3':{fontSize:'2.25rem'},'.enter':{alignItems:'flex-start',flexDirection:'column'},'.twocol':{gap:28},'.footer':{flexDirection:'column',textAlign:'center'}},
  '@media(max-width:430px)':{'.specs':{gridTemplateColumns:'1fr'},'.side':{gridTemplateColumns:'1fr'},'.consolefoot':{gridTemplateColumns:'1fr'},'.consolefoot div:nth-of-type(n+2)':{display:'none'}}
});

export default function HomeScreen({onPlay,hidden}){
  const[rows,setRows]=useState([]);const[status,setStatus]=useState('SYNCING');
  useEffect(()=>{let live=true;fetchLeaderboard(5).then(d=>{if(live){setRows(d);setStatus(d.length?'LIVE':'EMPTY')}}).catch(()=>live&&setStatus('OFFLINE'));return()=>{live=false}},[]);
  return <Page style={{display:hidden?'none':'block'}}>
    <div className="wrap nav"><a className="brand" href="#top"><span className="logo">K</span><span className="brandtext"><b>KRAUZER</b><small>GAMES</small></span></a><nav className="links"><a href="#top">Discover</a><a href="#games">Games</a><a href="#rankings">Rankings</a></nav><a className="navbtn" href="#games"><span>Explore Library</span><ArrowUpRight size={14}/></a></div>
    <div className="wrap hero" id="top"><div><div className="kicker"><i/>GAMING SYSTEM // ONLINE</div><h1>PLAY THE <span>FUTURE.</span></h1><p className="lead">A browser-first gaming platform for original arcade, action, strategy, RPG, and experimental worlds. Fast entry, clean competition, zero launcher nonsense.</p><div className="actions"><a className="primary" href="#games"><Gamepad2 size={16}/>Explore Games<ArrowRight size={16}/></a><button className="secondary" onClick={onPlay}><Play size={14} fill="currentColor"/>Play Featured</button></div><div className="stats"><div><small>LIBRARY</small><b>01 LIVE TITLE</b></div><div><small>PLATFORM</small><b>BROWSER NATIVE</b></div><div><small>NETWORK</small><b>RANK SYNC LIVE</b></div></div></div>
      <div className="console"><div className="consolebar"><span>KG // COMMAND INTERFACE</span><span className="online">● SYSTEM ONLINE</span></div><div className="consolegrid"><div className="core"><div className="floor"/><div className="orb"><Hexagon size={46}/></div><span className="micro m1">RENDER // READY</span><span className="micro m2">LATENCY // LOW</span><span className="micro m3">NODE // KG-01</span></div><div className="side"><div className="databox"><header><span>ACTIVE WORLD</span><Activity size={15}/></header><div><strong>01</strong><p>Playable release currently online.</p></div></div><div className="databox"><header><span>RANK SERVICE</span><Trophy size={15}/></header><div><strong>LIVE</strong><p>Competitive scoring synced globally.</p></div></div></div></div><div className="consolefoot"><div><Cpu/><span><small>ENGINE</small><b>WEB RUNTIME</b></span></div><div><Globe2/><span><small>DELIVERY</small><b>EDGE READY</b></span></div><div><Shield/><span><small>STATUS</small><b>SECURE</b></span></div></div></div>
    </div>
    <div className="rail"><div className="wrap railin">{['ACTION','ARCADE','RPG','STRATEGY','COMPETITIVE','EXPERIMENTAL','ADVENTURE'].map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<6&&<i>◆</i>}</React.Fragment>)}</div></div>
    <section className="wrap section" id="games"><div className="sectionhead"><div><span>01 / GAME LIBRARY</span><h2>Choose your next world.</h2></div><p>The catalog starts with one title. The interface is built for many more.</p></div><article className="gamecard" onClick={onPlay} tabIndex={0}><div className="art"><div className="sun"/><div className="mount"/><span className="crystal c1"/><span className="crystal c2"/><span className="crystal c3"/><div className="arttop"><span className="live">● PLAYABLE NOW</span><span>KG-001</span></div><div className="arttitle"><small>ARCADE / SURVIVAL</small><b>SKY<br/>CRYSTAL<br/>RUN</b></div><button className="playorb" onClick={e=>{e.stopPropagation();onPlay()}}><Play size={17} fill="currentColor"/></button></div><div className="gamecopy"><span>FEATURED RELEASE</span><h3>Sky Crystal Run</h3><p>Fast aerial survival built around movement, scoring chains, power-ups, escalating waves, and competitive runs.</p><div className="specs"><div><small>GENRE</small><b>ARCADE</b></div><div><small>MODE</small><b>SOLO</b></div><div><small>INPUT</small><b>DESKTOP + MOBILE</b></div><div><small>STATUS</small><b>LIVE</b></div></div><div className="enter"><button onClick={e=>{e.stopPropagation();onPlay()}}>ENTER GAME →</button><small>NO INSTALL REQUIRED</small></div></div></article></section>
    <section className="wrap section twocol" id="rankings"><div className="copy"><span>02 / COMPETITION</span><h2>Scores should feel earned.</h2><p>Ranked titles feed a shared competitive layer designed for future seasons, profiles, challenges, and additional games.</p><button className="secondary" onClick={onPlay}><Crosshair size={14}/>Start Ranked Run</button></div><div className="ranking"><div className="rankhead"><div><small>GLOBAL NETWORK</small><b>TOP PLAYERS</b></div><span className="status">{status}</span></div><ol className="ranklist">{rows.length?rows.map((r,i)=><li key={r.player_name+'-'+i}><em>{String(i+1).padStart(2,'0')}</em><div><b>{r.player_name}</b><small>Wave {r.wave} · {r.distance}m</small></div><strong>{r.score}</strong></li>):<li><em>01</em><div><b>No ranked runs yet</b><small>The board is waiting.</small></div><strong>—</strong></li>}</ol></div></section>
    <section className="wrap section"><div className="sectionhead"><div><span>03 / PLATFORM SYSTEMS</span><h2>Built for more than one game.</h2></div><p>Reusable library, shared competition, responsive UI, and room for larger releases without rebuilding the identity every month.</p></div><div className="specs"><div><small>LIBRARY</small><b>MULTI-TITLE READY</b></div><div><small>COMPETITION</small><b>SHARED RANKING LAYER</b></div><div><small>DELIVERY</small><b>INSTANT WEB ACCESS</b></div><div><small>FUTURE</small><b>MORE GENRES PLANNED</b></div></div></section>
    <footer className="wrap footer"><a className="brand" href="#top"><span className="logo">K</span><span className="brandtext"><b>KRAUZER</b><small>GAMES</small></span></a><span>ORIGINAL WORLDS // ONE EVOLVING PLATFORM</span><span>© 2026 KRAUZER GAMES</span></footer>
  </Page>
}